### ISSUE TITLE
Search fields: Enable enhanced usability with webkit-search-cancel-button

### ISSUE THREAD

**Issue by alexhass** [yamlcss/yaml#32]
I've seen that "webkit-search-cancel-button" has been disabled in base.css. I understand that it makes sense to style input form's all the same way, but removing this extreme useful feature from search inputs looks not like a good idea to me. It's not about style, it's about "usability". It was the key fact to change all my search text fields to type "search".

We should not remove these usability only for the reason that Chrome and Safari are currently the first browsers with this feature.

```
  input[type="search"]::-webkit-search-cancel-button,
  input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
  }
```

**Comment by djesse** [comment]
It is part of the normalisation process to make form elements look equal on all browsers. If you like this iOS only feature, you can set it active in your projects. As this is a non-standard feature, it should be a an intentional decision of the user, because - when the user adds a background image (e.g. magnifier icon) to the search field, this should look the same in all browsers by default.

**Comment by alexhass** [comment]
This feature is also available on Google Chrome on Desktops and this browser is extremely growing... :-)

**Comment by djesse** [comment]
Anyway ... non standard. That might change in the future.

**Comment by alexhass** [comment]
And for the notes... IE10 adds an X to every input to allow clearing the input... normalization also does not stop this. :-)
